services:
  postgis:
    container_name: postgis
    hostname: postgis
    image: postgis/postgis
    environment:
      - POSTGRES_USER=user #опционально
      - POSTGRES_PASSWORD=password #опционально
      - POSTGRES_DB=db_name #опционально
    volumes:
      -  postgis:/var/lib/postgresql/data/
    networks:
      postgis_pgadmin:
        ipv4_address: 10.10.10.3
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.ru #опционально
      - PGADMIN_DEFAULT_PASSWORD=password #опционально
    networks:
      postgis_pgadmin:
        ipv4_address: 10.10.10.2
    ports:
      - 8081:80 #порт 8081 опциональный, можно заменить на любой, который не занят
    restart: always

volumes:
  postgis:

networks:
  postgis_pgadmin:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

